version: "3.5"

services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: power-phrase2-front
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    networks:
      - app_network

networks:
  app_network:
    external: true
