version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:14

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run: npm run test

  deploy:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: VUE_APP_API_ENDPOINT=$VUE_APP_API_ENDPOINT VUE_APP_STATIC_FILE_ENDPOINT=$VUE_APP_STATIC_FILE_ENDPOINT VUE_APP_LOGIN_EMAIL=$VUE_APP_LOGIN_EMAIL VUE_APP_LOGIN_PASSWORD=$VUE_APP_LOGIN_PASSWORD npm run build
      - aws-s3/sync:
          from: dist
          to: s3://www.power-phrase.com/dist
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
